sudo: true
dist: trusty

before_install: sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install ia32-libs; sudo apt-get update; sudo apt-get install mit-scheme

script: make test

